### ISSUE TITLE
cs_instance pod and cluster selection

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#100]
I noticed that the UI allows for optionally selecting Pod and Cluster when creating a new instance.

Is that possible with ansible?

I cannot see any parameter in the documentation, except perhaps details for custom parameters.

Is that functionality missing?

**Comment by resmo** [comment]
Hi @rvalle 
The api was extended in http://docs.cloudstack.apache.org/en/4.13.0.0/releasenotes/api-changes.html, this is not yet implemented but shouldn't be too much work.

**Comment by resmo** [comment]
closed by #105
