### ISSUE TITLE
Unmaintained collection: Removal from the Ansible Community Package

### ISSUE THREAD

**Issue by mariolenz** [ngine-io/ansible-collection-cloudstack#129]
It looks like this collection is effectively unmaintained. According to the current [Ansible Community Package Collections Removal Process](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_package_removal.html#unmaintained-collections), we will consider removing it in a future version of the Ansible Community Package. Please see [Unmaintained collection: ngine_io.cloudstack](https://forum.ansible.com/t/6840) for more information.

At least one month after this announcement appears here and on [Bullhorn](https://forum.ansible.com/c/news/bullhorn/17), the Ansible Community Steering Committee will vote on whether this collection is considered unmaintained and will be removed, or whether it will be kept. If it will be removed, this will happen earliest in Ansible 12. Please note that people can still manually install the collection with `ansible-galaxy collection install ngine_io.cloudstack` even when it has been removed from the Ansible Community Package.

**Comment by resmo** [comment]
See my reaction https://forum.ansible.com/t/unmaintained-collection-ngine-io-cloudstack/6840
