### ISSUE TITLE
new style inventory plugin

### ISSUE THREAD

**Issue by resmo** [ngine-io/ansible-collection-cloudstack#26]
create a new style inventory plugin for virtual machines and routers

**Comment by rvalle** [comment]
I am happy to help.

**Comment by rvalle** [comment]
I would also like that the inventory plug-in would be able to get the credentials from the vault. But I don't know if that is possible.

I would also like to implement a grouping mechanism, perhaps using VM labels.

@resmo has you thought about it?

Of course we can also export whatever metadata we have from cloudstack as inventory variables (namespaced).

**Comment by resmo** [comment]
When implemented correctly, grouping by any key is just built-in with dynamic inventory. 

as an example in vultr, the api returns a `region: Amsterdam` and with a keyed group you can group by that region key: e.g. to group of `vultr_region_amsterdam` with all VMs in it and so on. 
```
plugin: vultr
keyed_groups:
  - prefix: vultr_region
    key: region | lower

There is even more groups mechanism possible beside `keyed_groups` and it is not much to investigate to get it all supported. There is dev docs about it and probably have a look at existing inventory plugins, e.g. https://github.com/ngine-io/ansible-collection-vultr/blob/master/plugins/inventory/vultr.py

**Comment by rvalle** [comment]
Yes I am looking at the docs, and samples and how other did. 

Allowing for selecting how to group hosts sounds like a good idea. I have also noticed that some plug-ins allow to select that actual hostname to use: IP address, or otherwise.

I was thinking that it would also be nice to be able to filter. Perhaps the obvious choice would be to restrict the inventory to a particular project only (optionally) vs perhaps the whole account.

**Comment by resmo** [comment]
allowing to filter based on zone and project would be nice indeed.

**Comment by rvalle** [comment]
great. working on it this week.

did you do integration test on the vultr plugin? trying to workout how to add tests to inventory plugins...

**Comment by rvalle** [comment]
AWS ec2 inventory is tested like this:
https://github.com/ansible-collections/amazon.aws/tree/main/tests/integration/targets/inventory_aws_ec2
They have a shell script as alternative entrypoint...

**Comment by rvalle** [comment]
yes... inventory tests are now called. It is very confusing that part of the testing infrastructure of the collection still ships into ansible and not in the collection itself. @resmo perhaps you should tell the core team.
