### ISSUE TITLE
Streamline simulator image to latest cloudstack release

### ISSUE THREAD

**Issue by resmo** [ngine-io/ansible-collection-cloudstack#32]
the integration tests run on an simulator image with cloudstack 4.11.

Container image repo https://github.com/ansible/cloudstack-test-container

**Comment by rvalle** [comment]
Which version should that be? 4.13 LTS or 4.14?

**Comment by resmo** [comment]
I prefer LTS because this is what most users use in production.

**Comment by resmo** [comment]
fixed with be2a0493f14bbc8fface5e3c1d21ae4ad462d78b
