### ISSUE TITLE
Documentation: Custom disk size and instances

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#37]
I think the documentation is wrong with regards to custom disk sizes.

In cs disk offering:

customized description is  "Whether the offering uses custom IOPS or not" but after looking at API and resting it, I think it should "Whether disk offering size is custom or not"

In cs instance:

disk_size  "Disk size in GByte required if deploying instance from ISO" but after testing it I think this is just the size of the data disk when a customized disk offering is used. I don't use ISOs myself but I would say that specifying the root_disk_size should then be mandatory in that case.

Can anybody confirm?

**Comment by resmo** [comment]
The doc is correct, with templates it is the size of the data disks, with iso, it is the size of the root disk.
