### ISSUE TITLE
Multiple CIDRs not working in VPC ACLs

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#41]
ACLs break if they specify multiple CIDRs, at least for Egress rules on VPCs
I can see in the UI that they are posted with several CIDRs separated by commas

When I add the second CIDR, the ACL breaks.

I am not sure if this is an Ansible module issue or an ACS, could be related to: https://github.com/apache/cloudstack/issues/4402

I have checked the API and it takes a list. I am not sure if we are translating it in a way that ACS likes it, or if ACS is failing to take a CIDR list on the ACL....

**Comment by resmo** [comment]
I fixed this some time ago for some modules e.g. for `cs_firewall` https://github.com/ngine-io/ansible-collection-cloudstack/blob/master/plugins/modules/cs_firewall.py#L49

**Comment by rvalle** [comment]
Our tests pass because the ACS Management server accepts the calls.

However, the problem is that the ACLs are not translated into VR Rules that actually work.

**Comment by resmo** [comment]
I would say so, yes.

**Comment by rvalle** [comment]
Lets close this issue as this is in fact an ACS issue by not meeting its own specification.
