### ISSUE TITLE
Configuration at module level is broken

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#51]
cloudstack modules can be configured via 3 diferent ways

- environment variables
- cloudstack ini files
- module supplied parameters

If environment parameters are not supplied ini search path will kick in. A SystemExit exception is raised if no ini file is supplied.

The code responsible for reading configuration from modules is unreachable if no ini file is present.

Therefore using a cloudstack ansible module configured only via module parameters does not work and the following exception is raised instead:

'''
Config file not found. Tried /home/ansible/.cloudstack.ini, /ansible/cloudstack.ini
'''

or similar.

**Comment by resmo** [comment]
related #64

**Comment by rvalle** [comment]
#64 has fixed this issue.
