### ISSUE TITLE
Deprecate cloudstack.ini configuration

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#59]
As discussed, 

>     the current logic with "reading config
>     from ini file" to get the keys is too error prone and think of
>     completely getting rid of it.
> 
>     As a consequence, only ansible parameter (and ansible env vars
>     fallback) would be available to users to auth

We can use the introduction of Ansible 3 to make this backward uncompatible change

**Comment by rvalle** [comment]
@resmo shall we say that:

- **v1.2.x** will require Ansible 3.x 
- **v1.1.x** remaining as Ansible 2.x support

**Comment by resmo** [comment]
fixed by #64
