### ISSUE TITLE
Deprecate default zone

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#60]
Since the introduction of UI sorting features in ACS the underlying zone API became unreliable.

Commit https://github.com/ngine-io/ansible-collection-cloudstack/commit/be2a0493f14bbc8fface5e3c1d21ae4ad462d78b addressed the issue by encouraging users to provide a zone parameter through a deprecation warning.

The default zone should be deprecated with the upcoming Ansible 3 release support, since this is a breaking change.

**Comment by resmo** [comment]
fixed by #62
