### ISSUE TITLE
cs_instance - ip_to_networks does not support mac address

### ISSUE THREAD

**Issue by jdinner** [ngine-io/ansible-collection-cloudstack#78]
Hello,
I need for my project set MAC address. From [Apache CloudStack API documentation ](https://cloudstack.apache.org/api/apidocs-4.15/apis/deployVirtualMachine.html) I read:
_iptonetworklist | ip  to network mapping. Can't be specified with networkIds parameter.  Example:  iptonetworklist[0].ip=10.10.10.11&iptonetworklist[0].ipv6=fc00:1234:5678::abcd&iptonetworklist[0].networkid=uuid&**iptonetworklist[0].mac=aa:bb:cc:dd:ee::ff**  - requests to use ip 10.10.10.11 in network id=uuid_

According to parameters of cs_instance. This should be possible via `ip_to_networks`, but only name (converted to networkid) and ip is passed. As you can see [here](https://github.com/ngine-io/ansible-collection-cloudstack/blob/e6e11e4f58ab965ef4e41bd2f4365cd9e329182e/plugins/modules/cs_instance.py#L573).

Can you, please, repair it or do you accept pull requests?

**Comment by rvalle** [comment]
hi @jdinner, what is your use case?

Is it for L2 networks?

I am not completely sure if the mac address can be set for all network providers, I am actually interested in setting up the mac address for virtual routers, but I am not sure it is possible.

This project certainly accepts pull requests.

**Comment by resmo** [comment]
closed by #81

**Comment by jdinner** [comment]
Sorry about writting into closed issue. I want only response: My use case is: I need VM with predefined MAC address because of software license I need to use, is released for a certain MAC address. Ansible should spawn VM, install SW and after work expunge this VM (second playbook).
