### ISSUE TITLE
Module cs_sshkeypair throws error CloudStackException: JSON (application/json) was expected, got 'text/html; charset=utf-8'

### ISSUE THREAD

**Issue by John222** [ngine-io/ansible-collection-cloudstack#95]
Hello guys

we found an issue with the ngine_io.cloudstack.cs_sshkeypair module. When we trying to use it, it throws the following error.

```bash
CloudStackException: JSON (application/json) was expected, got 'text/html; charset=utf-8'
```

as API URL we entered ```https://api.exoscale.ch```. We also tried with the url ```https://api.exoscale.com```.

Looks like exoscale changed the required header, which needs to be passed to the requests.

**Comment by resmo** [comment]
Hi @John222 

You got an unexpected html response from the endpoint, 

looking at the endpoint this should be either `https://api.exoscale.com/v1` or `https://api.exoscale.com/compute`. You can actually open this in your browser to check, the response should look like 

```json
{"errorresponse":{"errorcode":401,"cserrorcode":9999,"errortext":"unable to verify user credentials and/or request signature","uuidList":[]}}
```

**Comment by John222** [comment]
Thank you for the quick reply. I'll try it out and come back to you. 👍😃

**Comment by resmo** [comment]
That said, you reminded me to publish my  role for managing exoscale resources. Long overdue. Expect it to be released today.

**Comment by John222** [comment]
Hello Rene. It worked. Thank you for the hint. :).
