### ISSUE TITLE
disk_size parameter for cs_instance not working

### ISSUE THREAD

**Issue by John222** [ngine-io/ansible-collection-cloudstack#97]
Hello @resmo

it seems that disk_size parameter for ngine_io.cloudstack.cs_instance is not working. The disk size is always based on the service offering which have been choosen for the server.

**Comment by resmo** [comment]
Please check the docs and (hint, hint) use or see my exoscale role how params make sense in context of exoscale. you probably looking for https://docs.ansible.com/ansible/latest/collections/ngine_io/cloudstack/cs_instance_module.html#parameter-root_disk_size
